sources: 
  - fawazahmed0:
    - https://cdn.jsdelivr.net/gh/fawazahmed0/currency-api@1
  - frankfurter:
    - https://api.frankfurter.app
valid_currencies:
  - AED
  - AFN
  - ALL
  - AMD
  - ANG
  - AOA
  - ARS
  - AWG
  - AZN
  - BAM
  - BBD
  - BCH
  - BDT
  - BHD
  - BIF
  - BMD
  - BND
  - BOB
  - BSD
  - BTC
  - BTN
  - BWP
  - BYR
  - BZD
  - CDF
  - CHF
  - CLF
  - CLP
  - CNH
  - COP
  - CRC
  - CUP
  - CVE
  - CZK
  - DJF
  - DKK
  - DOP
  - DZD
  - EGP
  - ETB
  - ETH
  - EUR
  - FJD
  - GEL
  - GHS
  - GMD
  - GNF
  - GQE
  - GTQ
  - GYD
  - HNL
  - HRK
  - HTG
  - HUF
  - IQD
  - IRR
  - ISK
  - JMD
  - JOD
  - KES
  - KGS
  - KHR
  - KMF
  - KPW
  - KRW
  - KWD
  - KYD
  - KZT
  - LAK
  - LBP
  - LKR
  - LRD
  - LSL
  - LTC
  - LYD
  - MAD
  - MDL
  - MGA
  - MKD
  - MMK
  - MNT
  - MOP
  - MRU
  - MUR
  - MVR
  - MWK
  - MZM
  - MZN
  - NAD
  - NGN
  - NIO
  - NOK
  - NPR
  - OMR
  - PAB
  - PEN
  - PGK
  - PKR
  - PYG
  - QAR
  - RON
  - RSD
  - RWF
  - SAR
  - SBD
  - SCR
  - SDG
  - SEK
  - SHP
  - SLL
  - SOS
  - SRD
  - SVC
  - SYP
  - SZL
  - TJS
  - TMT
  - TND
  - TOP
  - TTD
  - TWD
  - TZS
  - UAH
  - UGX
  - UYU
  - UZS
  - VEF
  - VND
  - VUV
  - XAF
  - XCD
  - XOF
  - XPF
  - YER
  - ZMW
  - AUD
  - BGN
  - BRL
  - CAD
  - CNY
  - GBP
  - HKD
  - IDR
  - ILS
  - INR
  - JPY
  - MXN
  - MYR
  - NZD
  - PHP
  - PLN
  - RUB
  - SGD
  - THB
  - TRY
  - USD
  - ZAR